name: sliver_center
description: "A sliver that centers its child sliver within itself, primarily designed for centering slivers wrapped in SliverConstrainedCrossAxis."
version: 1.1.1
homepage: https://github.com/DemienIlnutskiy/sliver_center

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: any

dev_dependencies:
  flutter_test:
    sdk: flutter

