name: sliver_center
description: "A sliver that centers its child sliver within itself, primarily designed for centering slivers wrapped in SliverConstrainedCrossAxis."
version: 1.0.0+1
homepage: https://github.com/DemienIlnutskiy/sliver_center

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

